import type { PortfolioAccountSummary } from "./portfolio.types";

export const portfolioAccountSnapshots: PortfolioAccountSummary[] = [
  {
    id: "apple-card",
    institution: "Goldman Sachs",
    accountName: "Apple Card",
    productType: "credit-card",
    accountStatus: "current",
    dataStatus: "statement-snapshot",
    asOfDate: "2026-06-30",
    currentBalance: 6598.1,
    statementBalance: 6598.1,
    paymentDueDate: "2026-07-31",
    aprPercent: 25.49,
    creditLimit: 10000,
    notes: "June 2026 statement snapshot.",
  },
  {
    id: "amex-platinum",
    institution: "American Express",
    accountName: "Platinum Card",
    productType: "charge-card",
    accountStatus: "current",
    dataStatus: "statement-snapshot",
    asOfDate: "2026-06-08",
    currentBalance: 3782.21,
    statementBalance: 3782.21,
    minimumPaymentDue: 122.96,
    paymentDueDate: "2026-07-03",
    aprPercent: 26.49,
    creditLimit: 30000,
    notes: "Includes Pay Over Time balance.",
  },
  {
    id: "capital-one-quicksilverone",
    institution: "Capital One",
    accountName: "QuicksilverOne",
    productType: "credit-card",
    accountStatus: "past-due",
    dataStatus: "statement-snapshot",
    asOfDate: "2026-06-13",
    currentBalance: 7479.98,
    statementBalance: 7479.98,
    minimumPaymentDue: 255,
    paymentDueDate: "2026-07-08",
    aprPercent: 28.23,
    creditLimit: 7500,
    notes: "Statement includes a past-due fee.",
  },
  {
    id: "citi-aadvantage",
    institution: "Citibank",
    accountName: "AAdvantage Platinum Select",
    productType: "credit-card",
    accountStatus: "past-due",
    dataStatus: "statement-snapshot",
    asOfDate: "2026-06-25",
    currentBalance: 13407.14,
    statementBalance: 13407.14,
    minimumPaymentDue: 1395.97,
    paymentDueDate: "2026-07-23",
    aprPercent: 29.49,
    creditLimit: 15400,
    notes: "Minimum payment includes a past-due amount.",
  },
  {
    id: "macys-card",
    institution: "Citibank",
    accountName: "Macy's Card",
    productType: "store-card",
    accountStatus: "current",
    dataStatus: "statement-snapshot",
    asOfDate: "2026-06-29",
    currentBalance: 1736.7,
    statementBalance: 1736.7,
    minimumPaymentDue: 67.34,
    paymentDueDate: "2026-07-26",
    aprPercent: 32.74,
    creditLimit: 7600,
    notes: "Contains multiple interest-rate balance segments.",
  },
  {
    id: "dell-pay",
    institution: "Comenity Capital Bank",
    accountName: "Dell Pay",
    productType: "store-card",
    accountStatus: "paid-off",
    dataStatus: "statement-snapshot",
    asOfDate: "2025-04-15",
    currentBalance: 0,
    statementBalance: 0,
    minimumPaymentDue: 0,
    paymentDueDate: "2025-05-10",
    aprPercent: 30.99,
    creditLimit: 2000,
    notes: "Completed deferred-interest financing plan.",
  },
  {
    id: "sallie-mae",
    institution: "Sallie Mae",
    accountName: "Student Loan",
    productType: "student-loan",
    accountStatus: "current",
    dataStatus: "statement-snapshot",
    asOfDate: "2026-06-19",
    currentBalance: 19034.64,
    minimumPaymentDue: 239.88,
    paymentDueDate: "2026-07-14",
    aprPercent: 15.29,
    originalPrincipal: 18900,
    notes: "Currently in an interest-only repayment phase.",
  },
];
